name: jephchen
favicon: null
layout_spectrum: 0.42355333804152906
typography_spectrum: 0.46816379274241626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.94949936773628
  lightness: 0.4949354203417897
  saturation: 0.9227246034424752
  rhythmicContrast: 0.6737914450932294
purpose: []
